version: '3.7'

services:

  frontend:
    build:
      context: ./frontend
    image: react-frontend:1.0.0 
    ports:
      - "80:80"
    networks:
      - app-net
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: spring-backend:1.0.0 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 1s
      retries: 2
      start_period: 5s
    ports:
      - "8080"
    networks:
      - app-net
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: board
    ports:
      - "3306:3306"
    networks:
      - app-net
      
networks:
  app-net: