version: '3.7'

services:

  frontend:
    build:
      context: ./frontend
    image: react-frontend:1.0.0
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - app-net
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    image: spring-backend:1.0.0
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 1s
      retries: 2
      start_period: 5s
    ports:
      - "8080"
    networks:
      - app-net
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: board
    ports:
      - "3306:3306"
    networks:
      - app-net

  prometheus:
    build:
      context: ./prometheus
    image: my-prometheus:1.0.0
    ports:
      - "9090:9090"
    networks:
      - app-net

  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-net

networks:
  app-net:
