spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:mysql://db:3306/board?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: false
        # format_sql: true
        # use_sql_comments: true
        default_batch_fetch_size: 100

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
#  endpoint:
#    shutdown:
#      enabled: true # shutdown 엔드포인트 활성화

  endpoints:
    web:
      exposure: # env,beans 를 제외한 모든 엔드포인트 노출
        include: "*"
#        exclude: "env,beans"
